### ISSUE TITLE
v2 of PhpMetrics: roadmap and ideas

### ISSUE THREAD

**Issue by Halleck45** [phpmetrics/PhpMetrics#220]
Hi !

Edit: [this issue has been translated by C-Duv here.](https://github.com/phpmetrics/PhpMetrics/issues/220#issuecomment-217040620)

> Please note that [you'll find the associated PR here](https://github.com/phpmetrics/PhpMetrics/issues/220#issuecomment-217040620(https://github.com/phpmetrics/PhpMetrics/pull/221)

---

PhpMetrics fonctionne bien et est aujourd'hui stable, grâce au travail de tous les contributeurs. Je crois avoir à peu près respecté la vision initiale : offrir un moyen simple et ludique de disposer de métriques sur son code source.

Cependant, **il y a un défaut de conception majeur**. A l'origine, j'ai conçu cet outil comme une "preuve de concept" (poc), et mon unité de base était le fichier.

J'ai ajouté un certain nombre d'analyseurs de code (Halstead, McCabe...), mais à chaque fois en prenant comme réferentiel le fichier. Puis est apparu le besoin de travailler sur des objets PHP. Que faire ? J'ai procédé à une rustine : le parsage du code objet est un analyseur comme un autre, bien qu'il soit utilisé à peu près partout.

Il en résulte des **lourdeurs** (performande) et des **incohérences de conception**.

Par ailleurs, l'utilisation de la fonction `token_get_all()` a posé de nombreux problèmes : de performance, de RAM, mais aussi de cohérence. PHP manque de logique dans la nomenclature des tokens. 

Par exemple, en PHP, un `if` est représenté par le token `T_IF`, alors qu'une expression ternaire par le token `T_STRING` (le même qui sera utilisé pour les accolades `{` et `}` par exemple). Ce qui nous oblige à jongler en permanence avec des conditions pour tester la valeur du token avec le lequel on travaille...

Je souhaite **inverser les postulats et repartir de zéro**. Aujourd'hui, je connais mieux le besoin en terme de métriques, aussi j'ai refondu le code en posants les principes suivants:
- **le code objet est l'unité de base**. La première étape consiste à parser le code
- le parsage du code **ne dépend plus de la fonction `token_get_all()`** ni d'aucune fonction native
- le code est **représenté sous forme d'arbre**
- les composants de calcul de métrique travaillent au choix sur 
  - un arbre
  - un noeud de l'arbre
  - une classe
  - (rarement) un fichier
- le projet réduit ses dépendances externes

Par ailleurs, les rapports CLI (tableaux immenses affichés dans le terminal) ne semblent que très peu utilisés. Au contraire, le rapport HTML semble être l'outil de base. une refonte serait donc l'occasion de faire le tri dans les types de rapports d'analyse.

Le **passage à une représentation en graph permet aussi d'ajouter de nouvelles métriques**, aujourd'hui très difficiles à obtenir: NPath complexity, Hauteur de l'arbre moyen, représentation en arbre, diagramme UML...

Enfin, **j'ai réellement honte du diagramme "Evaluation"**, qui est sensé fournir une idée générale de l'état du projet. J'en ai honte car il n'est ni fiable ni cohérent. J'ai posé des mini-formules à-la-va-vite ; il en résulte quelque chose de fondamentalement inutile et contre-productif.

C'est pourquoi je [propose aujourd'hui une v2](https://github.com/phpmetrics/PhpMetrics/pull/221).

**J'aimerai avoir vos retours sur ces idées**.

Pour cela, **j'ai volontairement exclu tout code applicatif** (le code actuel ne contient que les analyseurs et les composants) : **j'aimerai d'abord recevoir des idées de chacun**, pour améliorer l'ergonomie de l'outil et le rendre encore plus utile.

**Si vous avez des idées, des choses à améliorer / changer dans les rapports, des métriques qui vous manque... n'hésitez donc pas à en faire part ici**.

Merci à tous de votre aide !

**Comment by Grummfy** [comment]
Je te réponds en anglais :
Hi, for me you should split the analyser libs and the app. Using libs permit to have smaller piece very focus and easy to refactor or to improve. If everything is in one giant stuff it will be unnecessarily complicated.
This split allows people to help you in an easier way and make your project more affordable for others. It can also allows some extension mechanism.

**Comment by YuraLukashik** [comment]
@Halleck45 hi, is there a slack room for discussions?

**Comment by Halleck45** [comment]
@YuraLukashik you can join this [gitter room](https://gitter.im/phpmetrics)

**Comment by YuraLukashik** [comment]
@Halleck45 I cannot :(
<img width="1014" alt="screen shot 2016-05-04 at 2 08 46 pm" src="https://cloud.githubusercontent.com/assets/4070636/15012523/f9487a5c-1201-11e6-8173-a13d1a5252f8.png">

**Comment by C-Duv** [comment]
Here is a translation proposal (I tried to stick closely with your idea).
Feel free to comment/adapt.

---

PhpMetrics works pretty well and is now, thanks to all his contributors, stable. I think I have fairly respected the initial goal: provide a simple and fun way of obtaining metrics about our source code.

Yet **it has a major design flaw**. At the beginning, I designed it as a proof of concept and, at that time, my base unit was the file.

I have added a fairly amount of code analyzers (Halstead, McCabe, ...) using file as a base reference, each time. Then the need to work on PHP objects occurred. Now what? I made a patch: parsing object code is then an analyzer like any other, even though it is used pretty much everywhere.

This leads to **slow performance** issues and **design inconsistencies**.

Moreover, using `token_get_all()` function caused a lot of problems: performance, RAM but also consistencies. PHP is missing some logic when naming tokens.

For example, in PHP, an `if` is represented by token `T_IF`, while a ternary expression by `T_STRING` (the same as braces `{` and `}` for example). Which forces us to permanently juggle with conditions to test the actual value of the token we're working on...

I want to **change theses initial assumptions and start from scratch**. Today I clearly see what are the needed metrics, thus I reworked the code around the following principles:
* **Object code is the base unit**. First step is parsing code
* Parsing code **does not uses `token_get_all()` anymore** nor any other native function
* Code is **represented as trees**
* Each component that computes metrics are working on either:
  * A tree
  * A tree node
  * A class
  * (rarely) a file
* Minimize project's external dependancies

Also, CLI reports (huge tables printed in the console) seems seldomly used. On the opposite, the HTML report seems the base feature. A redesign would be a good time to clean up among all the analysis report types.

**Moving to a tree representation gives access to new metrics**, currently very difficult to compute: NPath complexity, Average Hierarchy Height, tree representation, UML diagram, ...

At least, **I am really ashamed of the "Evaluation" diagram**, which is supposed to give a global idea of the project. It shames me because it is not reliable nor consistent. It uses quickly thought formulas; and produces a useless and counter-productive tool.

That is why I [announce a v2](https://github.com/phpmetrics/PhpMetrics/pull/221).

I would like your opinion on theses ideas.

In that goal, **I purposely omitted any applicative code** (current code only houses analyzers and components): **I would like to receive the ideas of everybody first**, to improve tool's functional design and make it more useful.

**If you have any idea, things to improve / change in reports, missing metrics, ... don't hesitate to manifest yourself here.**

Thanks to all for your help!

**Comment by clagiordano** [comment]
Hi,

I use PhpMetrics from several months, at work and at home, it is a wonderful project and I am very intresting about new feature.
I have read about the replace for token_get_all, there is a new php extension for this purpose but unfortunately works only with php >= 7.0, using the new php engine parser internal functions, but its can be a useful reading for the new approach to solving parser problems.

[https://github.com/nikic/php-ast](https://github.com/nikic/php-ast)

Thanks a lot for yours work!

**Comment by Halleck45** [comment]
@C-Duv Woohoo ! Thanks a lot !! Nice work ! Really :clap: 

@Grummfy yes, that's an idea

@clagiordano I don't want to use any extension. I've already wrote a [Tokenizer for the v2 based on regex](https://github.com/phpmetrics/PhpMetrics/blob/v2/src/Hal/Component/Token/Tokenizer.php)

@YuraLukashik I don't know how to open this room in gitter :cry:

**Comment by mnapoli** [comment]
@Halleck45 writing your own parser, especially based on regexes, will be a pain to write and maintain I'm afraid. PHP is a very complex language.

Why not rely on https://github.com/nikic/PHP-Parser ?

**Comment by tyx** [comment]
Hello !

Simple feedback.

It would be great to have a way to disable the requirement of phpDoc to run the analyze. 
Or to take care about method typehinting and return statement of PHP7 to complete the analyze.

Currently, the only metrics we cannot trust it is the MI because we don't use PHPdoc.

**Comment by Halleck45** [comment]
@mnapoli because [PHP-Parser requires extension](https://github.com/nikic/PHP-Parser/blob/master/composer.json#L14)

@tyx PhpMetrics takes care about typed PHP7 return statements ;)

**Comment by mnapoli** [comment]
@Halleck45 this is a standard extension, built in with PHP. A ton of project use PHP-Parser, it works without issues.

**Comment by tyx** [comment]
> @tyx PhpMetrics takes care about typed PHP7 return statements ;)

Good to hear ! 
But I never see it having an impact on MI like PhpDoc does. And I just give a new try and same result. A method with PHPDoc always give a better MI compare to the same method with typehinting of each attributes and return statement (and no phpdoc).
![](https://jumpshare.com/v/TJjSRLNfCdBi45vUHaLx+/Capture+d%E2%80%99e%CC%81cran+2016-05-06+a%CC%80+16.28.15.png)

**Comment by pavarnos** [comment]
@mnapoli i agree: the language is changing rapidly (some useful rfcs for 7.1). Maintaining a separate parser for phpmetrics is going to create a lot of extra work and affect compatibility. Building on an existing parser that is maintained by someone else will let this project focus on doing metrics (which it does very well!). ext-tokenizer is installed by default in many places and seems like a reasonable requirement. @Halleck45 check your own install: is it there?

**Comment by pavarnos** [comment]
https://github.com/sensiolabs-de/astrunner may be useful, which builds on https://github.com/nikic/PHP-Parser which seems very mature.

**Comment by mablae** [comment]
@Halleck45 Did you already put work into the frontend for v2 ? 

I looked at the code briefly in master and would like to implement a mobile friendly version and extends the SCSS to use more components directly from bootstrap-sass. 

Would it be okay to have a dev dependency on npm/webpack for better future proof maintainability? 
Also the the whole JS could be integrated into the offline version this version way better, to make it a truly offline thing. 

In other words: Just let me know if you want to have me put some work into making frontend a bit better maybe ? :+1:

Thanks for the phpmetrics by the way!

**Comment by mablae** [comment]
@Halleck45 I was also not able to join the gitter chat like @YuraLukashik . (No public room for phpmetrics org)

**Comment by Halleck45** [comment]
Hi,

after a long period of break, I've decided to work again on v2. I've started from scratch a [new branch](https://github.com/phpmetrics/PhpMetrics/tree/version2_ast)

So, on reflection, I'm agree that using the Nikic's PhpParser component is a good idea. I've also started a new UI:

![overview](https://cloud.githubusercontent.com/assets/1076296/17462319/649d6078-5ca9-11e6-9e94-98deaf59cf89.png)

This v2 is really different from v1:

+ PhpMetrics don't care of tokenization, and use external component
+ Introduced a `Graph` component
+ removed all "unnecessary" components
+ removed all "unnecessary" components
+ PHP 5.4 is needed

@mablae yes your help is welcome on UI . I cannot know how to open Gitter :(

@all What do you think of this new draft ?

Thanks !

**Comment by mablae** [comment]
@Halleck45 That looks really beautiful!

**Comment by pavarnos** [comment]
Wow! Really good! Looks like the code is under heavy development? Can you let us know when you are ready for some pull requests? 

- Ages ago i offered to write some documentation for the metrics: was thinking it could be stored internally as a php array then used in multiple places eg rendered in the html as a help page and used for tooltip hints, sent to the command line if a special flag is provided, etc
- I could add some extra report formats: eg csv summary (like the command line export in src/Hal/Report/Cli but in a single line with a timestamp that could be appended to a log file), csv detail (with all files listed), json summary (pretty printed), json detail (with all files, compact), excel (using phpoffice/phpexcel: might be better as a plugin?)
- interested to see how this performs on a large code base

**Comment by mablae** [comment]
@Halleck45 @pavarnos 👍 On modeling out the metrics: A single metric could be a class implementing an interface and this could then add additional metainformation like description, external links, and so on. The instances could be bootstrapped from an array due runtime.

**Comment by 20uf** [comment]
It is very good !

Is it not possible for you to define new formula in a chart to demonstrate the quality of the project?
I find the maintainability indicator is important information (it's a personal opinion)

**Comment by Halleck45** [comment]
@pavarnos @mablae  All good ideas are welcome :) . Indeed, metrics must be more documented. Each metric can be a class, or why not a simple PHP file in a `./doc/help` directory ?

@20uf v2 continues to have the Maintainability Index metric. However I think that the custom formula I made (about "accessibility for developers", "maintainability...") was really bugged. I don't find anywhere a "good formula" (and I doubt that it exists)

**Comment by dwenaus** [comment]
Wonderful project! an idea for v2: instead of three colors you could have a continuous range of color values.  It's easy to go gradually from green to yellow to red using HSV colors. http://stackoverflow.com/a/340214/545822

ps. my legacy codebase is mainly red, so it would be more informative to see what shade of red ;)

**Comment by Halleck45** [comment]
@dwenaus  That's look a good idea :+1:

**Comment by Halleck45** [comment]
v2 lives in master since few month. I close this issue

**Comment by Halleck45** [comment]
PhpMetrics v2 lives on `master` since few month, so I close this issue.

Thanks everyone !
