### ISSUE TITLE
use basic logic and diagrams for other languages

### ISSUE THREAD

**Issue by mi-schi** [phpmetrics/PhpMetrics#296]
Hi,

do you think it is possible to use the functionality of you tool for other languages like java? My idea is that I only need to rewrite the search pattern and can parse for example .java files and export your very good diagrams. Do you think multi-language is interesting for phpmetrics (javametrics) ;)

**Comment by niconoe-** [comment]
Hi,

You should see more in details with @Halleck45 but I think it would be another project.

The way phpMetrics works is parsing all tokens from PHP files and run complex intelligence using those tokens. Even if the complex intelligence may be exported to another language, the tokens this intelligence relies on are PHP tokens.

For Java, (based on your example), we will need to be able to tokenize java files and be able to manage the java tokens the same way they are managed by PHP in that complex  intelligence... which is very hard because java is not working like PHP ;).

What I mean is for example, it is possible to use polymorphism in Java while not possible in PHP...

So the complex intelligence doing the metrics is also related to the programing language, moreovre than the tokens to parse...

That is the main reason I think it would not be the job of PhpMetrics to do that, but the job of some kind of JavaMetrics tool.


Multi-language tool should be, IMO, only a tool that call all languages-specific tools and merge their results.

Please feel free to close this issue if I answered well your question ;).

**Comment by Halleck45** [comment]
Hi,

that was my first objective with v2 :)

PhpMetrics does not work on token (with v2), but on AST. In theory, we can analyse any AST based language (including Java).

If you find a Java parser (if you can convert Java vode to AST), I think that, in theory, you can deal with minor differences between langages... Maybe ^^

But that's a hard work !

Indeed
If you find a parser for Java

**Comment by niconoe-** [comment]
@Halleck45 Is that a wish to have PhpMetrics usable for other-languages projects? Or are you planning using the same algorithm but in another project "JavaMetrics", or "CSharpMetrics", or whatever?

Thanks.

**Comment by Halleck45** [comment]
Hum... I'll reply in french for simplicity :/

Comme je le disais, en théorie PhpMetrics peut le faire. Mais un projet en Go me paraîtrait plus logique / distribuable.

Si on devait le faire dans PhpMetrics, pourquoi pas, mais personnellement je ne me sens pas le temps ou l'énergie d'attaquer un tel chantier. Si quelqu'un voulait contribuer, il serait le bienvenue. Il y aurait juste un refactoring important, afin de garder une cohérence dans le code.

**Comment by niconoe-** [comment]
Dans ce cas, es-tu d'accord pour clôturer ce ticket tout en (re-)proposant à @mi-schi de proposer une PR avec tout ce chantier là ? Le ticket se pose comme une question à laquelle tu as répondu, par conséquent, il est traité.

Je m'occupe de traduire ton message dans le post ci-après.

**Comment by niconoe-** [comment]
From @Halleck45:
> As I said, PhpMetrics can do it in theory. But this kind of project should be done in Go, for distibution and understanding purposes.
> If we had to to it in PhpMetrics, why not, but I don't feel I'll have enough time or energy to start a huge work like this one. If someone wants to contribute, he'll be welcome to. There might just be an important refactoring in order to keep consistancy in the source code. Or, using a parser for each language in a docker container?

Then me @niconoe-:
> In this case, are you agree to close this issue with just asking (again?) to @mi-schi to propose a PR with all the work to do, done? This issue seems to only be a question at which you reply, so it is done.

**Comment by Halleck45** [comment]
@niconoe- Yes I'm agreee.

@mi-schi do not hesitate to open a PR on this subject ;)
