### ISSUE TITLE
File/directory explorer (as it was in v1)

### ISSUE THREAD

**Issue by liopic** [phpmetrics/PhpMetrics#322]
Hi,
I'm using phpMetrics 2.3.2 and it's a great tool; but I'm missing the old "Explore" link from phpMetrics v1 HTML report, where I could see a directory explorer and get metrics for directories and files.

Is there any plans to develop something similar for v2?

Thank you.

**Comment by niconoe-** [comment]
Hi, thank you for using PhpMetrics :).

Currently, there's an hidden HTML page called "all.html" where all metrics
for all files are displayed.
This is hidden because the design is really poor, due to its complexity to
make something clear here with a huge amount of data.
I don't know Halleck's plan for this, but if he doesn't have yet, I have
some in which we can discuss and find a way to make this page accessible
again.

Can you try to access it (by changing the URL) and tells me if this is the
kind of data you're looking for?

Thanks again,
Regards,


*Nicolas GIRAUD*Web Development Engineer
Zend Certified Engineer PHP 5.3
<http://www.zend.com/fr/store/education/certification/yellow-pages.php#show-ClientCandidateID=ZEND023390>

nicolas.giraud.dev@gmail.com
Port. : +33(0) 6 79 36 13 36

Aareon France
9, rue Jeanne Braconnier
92360 Meudon-la-Forêt
FRANCE

2017-10-25 11:24 GMT+02:00 Julio Martinez <notifications@github.com>:

**Comment by liopic** [comment]
Thank you for the tip... Actually I was looking for this data, but also data aggregated by directories. For instance, in phpMetrics v1 it was easy to spot smelly directories, so I can get a general overview of the quality of the code based in its structure. I don't know if this aggregated data is also being calculated internally in v2, and this could be displayed in the future.

Kind regards!

**Comment by niconoe-** [comment]
The aggregation is not calculated yet, but would be.
This will be a new feature for the all.html file.
Thanks for your feedback
