### ISSUE TITLE
Alternative on Ruby On Rails

### ISSUE THREAD

**Issue by xero88** [phpmetrics/PhpMetrics#324]
Hi,

This library is awesome. But i'm working now with an Ruby on Rails app. Is there a similar project on RoR ?

Thanks !

**Comment by niconoe-** [comment]
Hi,

I found some here: https://www.ruby-toolbox.com/categories/code_metrics.html (SimpleCov, rubocop, Rails best practices,...) but as I'm not fluent in Ruby, I don't practice them, you should give it some tries :).

It is a long road to make PhpMetrics compliant with other object languages (that's why PhpMetrics v2 is using AST), and it is not planned to make somthing callable for ruby project right now.
But if you are really interested, you can try to implement something with a PR :+1: 

Thanks.

**Comment by xero88** [comment]
Thanks for you answer!

I will maybe do that for side project =)
By the way, what is AST ?

**Comment by andreyors** [comment]
Abstract Syntax Tree
