### ISSUE TITLE
Formula for Maintainability index

### ISSUE THREAD

**Issue by krukru** [phpmetrics/PhpMetrics#325]
I noticed that the formula for maintainability index takes into consideration code comments. We frequently try to keep comments to a minimum and use self-explanatory code and php7 types whenever possible. Sadly this means we are almost aways 20 points down on the MI because of no phpdocs.

The formula you use is a small derivation of the original formula (see [reference](http://www.projectcodemeter.com/cost_estimation/help/GL_maintainability.htm)).

I would like to be able to provide a custom implementation for calculating MI, Microsoft Visual Studio formula looks very promising. Do you think that this can be done? I could help with a PR, just point me in the right direction.

**Comment by niconoe-** [comment]
Hi!

The reference your are pointing seems to be a bit wrong according to my research.

The original formula written by Paul Oman and Jack Hagemeister in 1992 and promoted by the SEI in 1997 is the one with the percentage of the lines of comments.
If you get deeper in the formula, you may also see that the "magic" 2,4 constant is just an approximation of the real value (pi²/4), that's why you can sometimes find the "magic" constant to "2,46" instead of "2,4".

The formula without comment is a simpler formula in case of no usage of documentation in the metrics (foreign language from a fetch foreign project so docs are unreadable, very old and unconsistants docs, ...)

The formula with comments has a range [0;221[
The formula without comments has a range [0;171]

The Visual studio's formula is just the same as the formula without comments but spread on a 100% line. This means if the formula without comments says your class have an MI of 171, the MVS's formula will say your MI is 100. For a MI (without comments) of 85,5, MVS will say 50.

To me, there are only 2 formulas, but the one without comments is not really relevant if you have projects with real usefull documentation pieces in. Indeed, I'm not sure about implementing it into a second MI calculation, but if that's something you really need, I will let you make a PR for this. But it must be a new value that must not be taking into account in the MI graphic and some valuable reports.

BTW, using self-explanatory code with php7 types are good things to quickly understand the basics, but a PHPDoc or some inline comments for tricky business part of your project are really recommanded.

**Comment by pattisahusiwa** [comment]
+1 for Maintainability Index Without comment.

It would be nice if we can add the option in console argument (configuration) instead of this

> An idea can be to add a checkbox "exclude comments for calculation of maintainability". If checked, graph use the MIwoc instead of the Mi. What do you thin about this proposition ?

**Comment by niconoe-** [comment]
@Halleck45 As this is released in 2.6, do you think we can close that issue?

**Comment by niconoe-** [comment]
New option is available since v2.6 to use MI or MIwoc, letting the choice to the end user.

Closing this issue as solved.
