### ISSUE TITLE
Do not override default exclude list

### ISSUE THREAD

**Issue by mxr576** [phpmetrics/PhpMetrics#364]
If I provide custom exclude list with `--exclude` parameter the "sane" default [exclusion list](https://github.com/phpmetrics/PhpMetrics/blob/1a3c100891fe60e401fb0b2c136a689eecb398c3/src/Hal/Application/Config/Validator.php#L33) should not be overridden rather extended or it should be configurable whether I would like to override or just extend it.

Version: 2.4.1

**Comment by niconoe-** [comment]
Actually, I'm not a fan of keeping the default exclusion list when providing a custom `--exclude` option. Like it is defined, the list is a default value, not something hardly written. If you want not to  exclude those items in the list, then just override the default value with your own. 

My opinion is:
Either you want to add excluded items, and so you need to explicitly say "I want to exclude the default items + mine", and in that case, just write the default items + yours;
Either you want to clearly define the excluded items, and you just use the option like it is currently designed for.

What's your opinion @gmponos , @Halleck45 ?

**Comment by enrico69** [comment]
@Halleck45 ?

**Comment by Halleck45** [comment]
Hi,

I'm agree. Forcing a exclusion list will cause troubles in lot or cases.

However, we can imagin add this list in the documentation, or a link to the source code... @mxr576, do not hesitate to contribute 🙂

**Comment by mageekguy** [comment]
Hi everybody.

I'm confirming that usage of `--exclude` imply complete overriding of default exclusion list is VERY disturbing : I have lost half a day to try to understand why `phpmetrics` report contains more LOC when it is used…

So, I have two suggestions :

- Add something in the documentation related to `--exclude` like "Be aware that using this argument override completely the default exclusion list when it is used, so metrics in report can have some different value (for example more LOC)";
- Displaying/Writing the exclusion list used during analyze in the report, and maybe the list of files analyzed.

And I'm sorry, because, I have no enough time to do the according PR ;).

Thanks for your work, by the way.

My (only) 2 cents, but 2 cents is better than nothing :D.

Best regards,
Fred.

**Comment by Halleck45** [comment]
thanks @mageekguy for the feedback!

I've just opened #541:

The `--exclude` behavior is unchanged: a custom list still replaces the default one. But it's no longer silent:
- the --help text now documents it and shows the default list;
- a warning is displayed when vendor files actually end up in the analysis (see screenshot below), which is the typical way to get inflated LOC without noticing.

<img width="1059" height="636" alt="Image" src="https://github.com/user-attachments/assets/eea0b5d6-0cb8-4171-bfc1-f629a4e2b582" />

What do you think about this solution ?

**Comment by Halleck45** [comment]
Hi,

I close this issue (#541 is now merged). Feel free to reopen it if needed
