### ISSUE TITLE
Fatal error: Uncaught Error: Class 'Hal\Component\Ast\NodeTraverser' not found in src/Hal/Application/Analyze.php:84

### ISSUE THREAD

**Issue by pavarnos** [phpmetrics/PhpMetrics#373]
I've installed PhpMetrics 2.4.1 with composer

When I run this command:
```
phpmetrics src
```

I get this output:

```
Fatal error: Uncaught Error: Class 'Hal\Component\Ast\NodeTraverser' not found in vendor/phpmetrics/phpmetrics/src/Hal/Application/Analyze.php:84
Stack trace:
#0 vendor/phpmetrics/phpmetrics/src/Hal/Application/Application.php(59): Hal\Application\Analyze->run(Array)
#1 vendor/phpmetrics/phpmetrics/bin/phpmetrics(20): Hal\Application\Application->run(Array)
#2 {main} 
thrown in vendor/phpmetrics/phpmetrics/src/Hal/Application/Analyze.php on line 84
```

I think the problem is in `Component\Ast\NodeTraverser.php`. The file is called NodeTraverser.php but the class is called `Traverser`. The `class_alias` at the bottom does not appear to work for php7.3

**Comment by skyzyx** [comment]
This is biting me too.

**Comment by TrueXakeP** [comment]
I've discovered that this happens if the `--classmap-authoritative` flag passed to Composer. This error does not happen if only the `--optimize` flag is set.
I guess Composer do not parse class_alias() call.
This is so regardless of the version of PHP. 7.2 whether it is or 7.3
I can't tell if the NodeTraverser class can be pushed to the composer's class map explicitly to `--classmap-authoritative` can work.
But one solution I see is to define NodeTraverser as normal class and to make class alias of it's parent.
So update this:
https://github.com/phpmetrics/PhpMetrics/blob/39095017413805cd6d9ada16cfaf8aaffcb2fec4/src/Hal/Component/Ast/NodeTraverser.php#L98-L102
to this:
```php
if (PHP_VERSION_ID >= 70000) {
    class_alias(Php7NodeTraverser::class, __NAMESPACE__ . '\\NodeTraverserActual');
} else {
    class_alias(Php5NodeTraverser::class, __NAMESPACE__ . '\\NodeTraverserActual');
}

class NodeTraverser extends NodeTraverserActual
{
}
```
With this modification my PhpMetrics works normally with the `--classmap-authoritative` flag.

The other solution I see is to use the `--optimize` flag.
