### ISSUE TITLE
Exit code on violations in vendor binary

### ISSUE THREAD

**Issue by gisostallenberg** [phpmetrics/PhpMetrics#460]
# Feature request

Currently the vendor binary returns nothing, which makes it hard to integrate in any CI without the CI understanding PMD files.

I suggest to make `Hal\Application\Application::run` return the status (also where it has exit at the moment) and finally return either 0 (no violations) or 4 (violations). Then have `bin/phpmetrics` exit with the return value of that call.
The 4 exit status comes from https://pmd.github.io/latest/pmd_userdocs_cli_reference.html#exit-status
Because this might not be BC when `Hal\Application\Application::run` is used in other applications (although I cannot imagine them relying on `exit`) this behavior can also be added using an option `--report-status` and only add the exit in `bin/phpmetrics` for non null results.

I'm happy to provide a PR.

**Comment by niconoe-** [comment]
On v3.0.0rc4, phpmetrics returns 1 if any critical violation has been detected, and 0 otherwise.

You can define your own violation rules with the configuration file. 
See example: https://github.com/phpmetrics/PhpMetrics/blob/10f099e1dd0f45def6e511fd91809e0719f16f11/config-example.json#L24-L35

On this JSON object, when the property `failIfFound` is set to `true` and the related rule is violated, the exit status of phpmetrics will be 1 (error).

Feel free to define your own violation rules and adding a flag to know, for each one, if you want to consider this rule as critical or not, depending on your QA standards. Then you could use the exit status as a reference value for your CI integration 😉
